/*
* Copyright (c) 2019 Yellicode
*
* This Source Code Form is subject to the terms of the Mozilla Public
* License, v. 2.0. If a copy of the MPL was not distributed with this
* file, You can obtain one at http://mozilla.org/MPL/2.0/.
*/

/**
* This code was generated by a tool.
* 
* Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
*/
import * as elements from './interfaces';

export interface ElementComparer {
	compareOrderedElements<TElement extends elements.OrderedElement & elements.NamedElement>(x: TElement, y: TElement): number;
	comparePackageableElements<TElement extends elements.PackageableElement>(x: TElement, y: TElement): number;
}
